import Foundation
import CryptoKit

@main
struct PrivateHeaderKitBuildInfoTool {
    static func main() throws {
        let options = try Options.parse(arguments: CommandLine.arguments)
        let outputURL = URL(fileURLWithPath: options.outputPath)
        let version = try BuildVersionResolver.resolve(
            environmentVersion: options.environmentVersion,
            packageDirectory: URL(fileURLWithPath: options.packageDirectoryPath)
        )
        let source = BuildVersionResolver.generatedSource(version: version)

        try FileManager.default.createDirectory(
            at: outputURL.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )
        if let existing = try? String(contentsOf: outputURL, encoding: .utf8),
           existing == source
        {
            return
        }
        try source.write(to: outputURL, atomically: true, encoding: .utf8)
    }
}

private struct Options {
    let outputPath: String
    let packageDirectoryPath: String
    let environmentVersion: String?

    static func parse(arguments: [String]) throws -> Self {
        var outputPath: String?
        var packageDirectoryPath: String?
        var environmentVersion: String?
        var index = 1
        while index < arguments.count {
            switch arguments[index] {
            case "--output":
                outputPath = try value(after: index, in: arguments, for: "--output")
                index += 2
            case "--package-directory":
                packageDirectoryPath = try value(
                    after: index,
                    in: arguments,
                    for: "--package-directory"
                )
                index += 2
            case "--environment-version":
                environmentVersion = try value(
                    after: index,
                    in: arguments,
                    for: "--environment-version"
                )
                index += 2
            default:
                throw BuildInfoToolError.message("unknown option: \(arguments[index])")
            }
        }
        guard let outputPath else {
            throw BuildInfoToolError.message("--output is required")
        }
        guard let packageDirectoryPath else {
            throw BuildInfoToolError.message("--package-directory is required")
        }
        return Self(
            outputPath: outputPath,
            packageDirectoryPath: packageDirectoryPath,
            environmentVersion: environmentVersion
        )
    }

    private static func value(
        after index: Int,
        in arguments: [String],
        for option: String
    ) throws -> String {
        guard index + 1 < arguments.count else {
            throw BuildInfoToolError.message("\(option) requires a value")
        }
        return arguments[index + 1]
    }
}

package enum BuildVersionResolver {
    package struct DirtyInputRecord: Hashable, Sendable {
        package let path: String
        package let kind: String
        package let contentDigest: Data

        package init(path: String, kind: String, contentDigest: Data) {
            self.path = path
            self.kind = kind
            self.contentDigest = contentDigest
        }
    }

    package static func resolve(
        environmentVersion: String?,
        packageDirectory: URL,
        gitDescribe: (URL) throws -> String? = defaultGitDescribe(in:)
    ) throws -> String {
        if let version = try normalized(environmentVersion) {
            return version
        }
        if let version = try normalized(gitDescribe(packageDirectory)) {
            return version
        }
        throw BuildInfoToolError.message(
            "unable to determine PrivateHeaderKit build version; "
                + "set PRIVATEHEADERKIT_BUILD_VERSION or build from a Git checkout"
        )
    }

    package static func generatedSource(version: String) -> String {
        """
        // Generated by PrivateHeaderKitBuildInfoTool. Do not edit.

        package enum PrivateHeaderKitBuildInfo {
            package static let version = "\(escapedStringLiteral(version))"
        }
        """
    }

    private static func normalized(_ value: String?) throws -> String? {
        guard let value else { return nil }
        let normalized = value.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !normalized.isEmpty else { return nil }
        guard normalized.utf8.count <= 256,
              normalized.unicodeScalars.allSatisfy({ scalar in
                  switch scalar.properties.generalCategory {
                  case .control, .format, .lineSeparator, .paragraphSeparator:
                      false
                  default:
                      true
                  }
              })
        else {
            throw BuildInfoToolError.message(
                "build version must be a printable string of at most 256 bytes"
            )
        }
        return normalized
    }

    private static func defaultGitDescribe(in packageDirectory: URL) throws -> String? {
        guard let description = try gitOutputData(
            ["describe", "--tags", "--always"],
            in: packageDirectory
        ),
            let trackedDiff = try gitOutputData(
                [
                    "diff", "--no-ext-diff", "--no-textconv", "--binary", "HEAD", "--",
                    "Package.swift", "Package.resolved", "Plugins", "Sources",
                ],
                in: packageDirectory
            ),
            let untrackedPaths = try gitOutputData(
                [
                    "ls-files", "--others", "--exclude-standard", "-z", "--",
                    "Package.swift", "Package.resolved", "Plugins", "Sources",
                ],
                in: packageDirectory
            )
        else {
            return nil
        }
        let version = String(decoding: description, as: UTF8.self)
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !version.isEmpty else { return nil }
        let records = try untrackedInputRecords(
            pathsData: untrackedPaths,
            packageDirectory: packageDirectory
        )
        guard let fingerprint = dirtyFingerprint(
            trackedDiff: trackedDiff,
            untrackedRecords: records
        ) else {
            return version
        }
        return "\(version)-dirty.\(fingerprint)"
    }

    package static func dirtyFingerprint(
        trackedDiff: Data,
        untrackedRecords: [DirtyInputRecord]
    ) -> String? {
        guard !trackedDiff.isEmpty || !untrackedRecords.isEmpty else { return nil }
        var hasher = SHA256()
        appendCanonical(Data("privateheaderkit-dirty-input-v1".utf8), to: &hasher)
        appendCanonical(trackedDiff, to: &hasher)
        for record in untrackedRecords.sorted(by: { lhs, rhs in
            lhs.path.utf8.lexicographicallyPrecedes(rhs.path.utf8)
        }) {
            appendCanonical(Data(record.path.utf8), to: &hasher)
            appendCanonical(Data(record.kind.utf8), to: &hasher)
            appendCanonical(record.contentDigest, to: &hasher)
        }
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }

    private static func untrackedInputRecords(
        pathsData: Data,
        packageDirectory: URL
    ) throws -> [DirtyInputRecord] {
        try pathsData.split(separator: 0).map { bytes in
            let path = String(decoding: bytes, as: UTF8.self)
            guard !path.hasPrefix("/"),
                  !path.split(separator: "/").contains("..")
            else {
                throw BuildInfoToolError.message(
                    "Git reported an unsafe untracked source path: \(path)"
                )
            }
            let url = packageDirectory.appendingPathComponent(path, isDirectory: false)
            let attributes = try FileManager.default.attributesOfItem(atPath: url.path)
            switch attributes[.type] as? FileAttributeType {
            case .typeRegular:
                return DirtyInputRecord(
                    path: path,
                    kind: "regular",
                    contentDigest: try fileDigest(at: url)
                )
            case .typeSymbolicLink:
                let destination = try FileManager.default.destinationOfSymbolicLink(
                    atPath: url.path
                )
                return DirtyInputRecord(
                    path: path,
                    kind: "symlink",
                    contentDigest: Data(SHA256.hash(data: Data(destination.utf8)))
                )
            default:
                throw BuildInfoToolError.message(
                    "untracked source input is not a regular file or symbolic link: \(path)"
                )
            }
        }
    }

    private static func fileDigest(at url: URL) throws -> Data {
        let handle = try FileHandle(forReadingFrom: url)
        defer { try? handle.close() }
        var hasher = SHA256()
        while let data = try handle.read(upToCount: 1024 * 1024), !data.isEmpty {
            hasher.update(data: data)
        }
        return Data(hasher.finalize())
    }

    private static func appendCanonical(_ data: Data, to hasher: inout SHA256) {
        var length = Data()
        let count = UInt64(data.count)
        for shift in stride(from: 56, through: 0, by: -8) {
            length.append(UInt8(truncatingIfNeeded: count >> shift))
        }
        hasher.update(data: length)
        hasher.update(data: data)
    }

    private static func gitOutputData(
        _ arguments: [String],
        in packageDirectory: URL
    ) throws -> Data? {
        let process = Process()
        let outputPipe = Pipe()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
        process.arguments = ["-C", packageDirectory.path] + arguments
        process.standardOutput = outputPipe
        process.standardError = FileHandle.nullDevice
        try process.run()
        let data = outputPipe.fileHandleForReading.readDataToEndOfFile()
        process.waitUntilExit()
        return process.terminationStatus == 0 ? data : nil
    }

    private static func escapedStringLiteral(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }
}

package enum BuildInfoToolError: Error, CustomStringConvertible {
    case message(String)

    package var description: String {
        switch self {
        case .message(let message): message
        }
    }
}
